use role accountadmin;
use schema emp_{{environment}}.public;

CREATE OR ALTER VIEW PUBLIC.EMPLOYEE_HIGH_SALARY
AS 
SELECT DISTINCT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY,HIRE_DATE 
FROM EMP_DEV.PRIVATE.EMPLOYEES
WHERE SALARY>=17000