use role accountadmin;
use schema emp_{{environment}}.public;

CREATE OR ALTER VIEW PUBLIC.EMPLOYEE_HIGH_SALARY
AS 
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY 
FROM EMP_DEV.PRIVATE.EMPLOYEES
WHERE SALARY>=17000